from PyQt5.QtWidgets import QPushButton, QVBoxLayout, QHBoxLayout , QLabel
from PyQt5.QtCore import Qt

btn1 = QPushButton("1")
btn2 = QPushButton("2")
btn3 = QPushButton("3")
btn4 = QPushButton("4")
btn5 = QPushButton("5")
btn6 = QPushButton("6")
btn7 = QPushButton("7")
btn8 = QPushButton("8")
btn9 = QPushButton("9")
btn0 = QPushButton("0")
btn_inverse = QPushButton("1/x")
btn_sqr = QPushButton("x^2")
btn_sqrt = QPushButton("√x")
btn_inv = QPushButton("+/-")
btn_coma = QPushButton(".")
btn_plus = QPushButton("+")
btn_minus = QPushButton("-")
btn_mul = QPushButton("*")
btn_delenie = QPushButton("/")
btn_ravno = QPushButton("=")
btn_C = QPushButton("C")
btn_CE = QPushButton("CE")
btn_prozent = QPushButton("%")
btn_otmena = QPushButton("<-")

label = QLabel("0")
label2 = QLabel("")

main_line = QVBoxLayout()
line1 = QHBoxLayout()
line2 = QHBoxLayout()
line3 = QHBoxLayout()
line4 = QHBoxLayout()
line5 = QHBoxLayout()
line6 = QHBoxLayout()
line_text = QVBoxLayout()

line1.addWidget(btn1)
line1.addWidget(btn2)
line1.addWidget(btn3)
line1.addWidget(btn_plus)

line2.addWidget(btn4)
line2.addWidget(btn5)
line2.addWidget(btn6)
line2.addWidget(btn_minus)

line3.addWidget(btn7)
line3.addWidget(btn8)
line3.addWidget(btn9)
line3.addWidget(btn_mul)

line4.addWidget(btn_inverse)
line4.addWidget(btn_sqr)
line4.addWidget(btn_sqrt)
line4.addWidget(btn_delenie)

line5.addWidget(btn_inv)
line5.addWidget(btn0)
line5.addWidget(btn_coma)
line5.addWidget(btn_ravno)

line6.addWidget(btn_prozent)
line6.addWidget(btn_CE)
line6.addWidget(btn_C)
line6.addWidget(btn_otmena)

line_text.addWidget(label2 , alignment = Qt.AlignRight)
line_text.addWidget(label , alignment = Qt.AlignRight)

main_line.addLayout(line_text)
main_line.addLayout(line6)
main_line.addLayout(line4)
main_line.addLayout(line3)
main_line.addLayout(line2)
main_line.addLayout(line1)
main_line.addLayout(line5)